### ISSUE TITLE
JWT Signature not matching exception being thrown.

### ISSUE THREAD

**Issue by ghost** [MosquitoKill3r/civic-api#1]
Hi, thank you so much for doing this implementation. I am stuck with this exception and can not figure out what to do.

io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

at com.civic.sip.CivicSip.verify(CivicSip.java:193) ~[classes/:na]

I have made sure the keys are correct but just can not get past this exception. 

I have made sure that the keys are correct but just not having any luck. I am running on http://localhost:9090 

Thanks a lot.

**Comment by MosquitoKill3r** [comment]
Hello,

Please make sure that you are using public key described in README. 
Please let me know if it works for you.

**Comment by ghost** [comment]
I got it working. Can you please point that out in the code and readme to use the public_key provided and not the one from Civic account public key..
